plugins {
    id 'java'
}

group = 'com.wykwey'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.2.build.119-stable'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
